name: flutter_bloc_pattern
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  equatable: ^0.6.1 
  flutter:
    sdk: flutter
  flutter_bloc: ^1.0.0
  logger: 0.7.0+2
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: 
  uses-material-design: true 
